# Generated by Django 3.1 on 2020-08-30 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='mame',
            new_name='name',
        ),
    ]
