# Generated by Django 3.1 on 2020-09-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200911_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='', verbose_name='img'),
            preserve_default=False,
        ),
    ]
