# Generated by Django 3.1 on 2020-09-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20200911_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pub_date',
            field=models.DateTimeField(default='', verbose_name='date_published'),
            preserve_default=False,
        ),
    ]
