# Generated by Django 3.0.6 on 2020-10-12 21:39

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='author_headshots', validators=[myapp.models.validate_image]),
            preserve_default=False,
        ),
    ]
